#!/bin/bash
#
# Generate a random password and store it in a file.
#
# Usage:
#
#   $ generate-password dest-file

set -euo pipefail

if [ $# -ne 1 ]
then
  echo "Usage: $0 dest-file"
  exit 1
fi

DESTFILE="$1"

# If the file exists, check if it contains the "---" string
if [ -f "$DESTFILE" ]
then
  if grep -Eq '^---+\s*$' "$DESTFILE"
  then
    echo "[WARN] Destination contains a separator ('---')."
    echo "[WARN] Password will not be visible for copy-lines."
  fi
fi

# Generate a new password with apg(1).
mkdir -p "$(dirname "$DESTFILE")"
apg -a1 -n1 -m24 -x32 -M NLC >> "$DESTFILE"
